name: Build and publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set version variable
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Create zip archive
        run: zip -r YouMaySpeak-${{ env.VERSION }}.zip . -x ".*"

      - name: Push release
        uses: softprops/action-gh-release@v1
        with:
          files: YouMaySpeak-${{ env.VERSION }}.zip

      - name: Upload to Nexus Mods
        id: upload
        uses: Nexus-Mods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_id: ${{ vars.NEXUSMODS_FILE_ID }}
          filename: YouMaySpeak-${{ env.VERSION }}.zip
          display_name: "You May Speak"
          version: ${{ env.VERSION }}
          update_mod_version: true
          primary_mod_manager_download: true
