name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Zip Archive
        run: |
          VERSION=${{ github.ref_name }}
          zip -r YouMaySpeak-${VERSION}.zip . -x ".*"


      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: YouMaySpeak-*.zip
