name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Zip Archive
        run: zip -r YouMaySpeak-${{ github.ref_name }}.zip . -x ".*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: YouMaySpeak-${{ github.ref_name }}.zip

      - name: Upload to Nexus Mods
        id: upload
        uses: Nexus-Mods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_id: ${{ vars.NEXUSMODS_FILE_ID }}
          filename: YouMaySpeak-${{ github.ref_name }}.zip
          display_name: "You May Speak"
          version: ${{ github.ref_name }}
          update_mod_version: true
